{% set name = "smi-analysis" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smi-analysis-{{ version }}.tar.gz
  sha256: 7b12febc1c97f415314aad183d4220867c790cff6f1c2c65de23fa942117a435

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - pyfai
    - pygix >=2022.11.14
    - scipy
    - xarray

test:
  imports:
    - smi_analysis
    - smi_analysis.tests
  commands:
    - pytest --pyargs smi_analysis.tests
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II-SMI/smi-analysis
  summary: Scientific Python for data analysis at the Soft Matter Interface (SMI) beamline at NSLS-II
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - gfreychet
